---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate: registry
    io.containers.autoupdate/app: local
    io.containers.autoupdate/web: local
  labels:
    app: cloud-pod
  name: cloud-pod
spec:
  automountServiceAccountToken: false
  containers:
    - image: localhost/cloud-web:latest
      name: web
      ports:
        - name: web
          containerPort: 80
      volumeMounts:
        - mountPath: /srv/de.dm-poepperl.cloud
          name: cloud-pvc
          readOnly: true
        - mountPath: /srv/de.dm-poepperl.cloud/data/appdata_och5khtk0i0u/preview
          name: cloud-preview-pvc
          readOnly: true
      livenessProbe:
        httpGet:
          path: /alive
          port: 80
        periodSeconds: 300
    - image: localhost/cloud:latest
      name: app
      volumeMounts:
        - mountPath: /srv/de.dm-poepperl.cloud
          name: cloud-pvc
        - mountPath: /srv/de.dm-poepperl.cloud/data/appdata_och5khtk0i0u/preview
          name: cloud-preview-pvc
      livenessProbe:
        exec:
          command:
            - /usr/bin/bash
            - /usr/local/bin/alive.sh
        periodSeconds: 300
    - image: docker.io/library/postgres:18-alpine
      name: db
      env:
        - name: POSTGRES_PASSWORD
          value: a
      volumeMounts:
        - mountPath: /var/lib/postgresql
          name: cloud-db-pvc
      livenessProbe:
        exec:
          command:
            - pg_isready
            - -U
            - postgres
        periodSeconds: 300
    - image: docker.io/nextcloud/aio-imaginary
      name: imaginary
      livenessProbe:
        exec:
          command:
            - wget
            - -q
            - --spider
            - localhost:9000/health
        periodSeconds: 300
    - image: docker.io/valkey/valkey:8-alpine
      name: redis
      livenessProbe:
        exec:
          command:
            - redis-cli
            - ping
        periodSeconds: 300
  volumes:
    - name: cloud-pvc
      hostPath:
        path: /var/mnt/persist/cloud
    - name: cloud-db-pvc
      hostPath:
        path: /var/mnt/persist/cloud/db
    - name: cloud-preview-pvc
      hostPath:
        path: /var/mnt/ephemeral/cloud-preview
