---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate: registry
    io.containers.autoupdate/app: local
    io.containers.autoupdate/web: local
  labels:
    app: cloud-pod
  name: cloud-pod
spec:
  automountServiceAccountToken: false
  containers:
    - image: localhost/cloud-web:latest
      name: web
      ports:
        - name: web
          containerPort: 80
          hostPort: 8088
      volumeMounts:
        - mountPath: /srv/de.dm-poepperl.cloud
          name: cloud-pvc
          readOnly: true
        - mountPath: /srv/de.dm-poepperl.cloud/data/appdata_och5khtk0i0u/preview
          name: cloud-preview-pvc
          readOnly: true
    - image: localhost/cloud:latest
      name: app
      volumeMounts:
        - mountPath: /srv/de.dm-poepperl.cloud
          name: cloud-pvc
        - mountPath: /srv/de.dm-poepperl.cloud/data/appdata_och5khtk0i0u/preview
          name: cloud-preview-pvc
      livenessProbe:
        exec:
          command:
          - /usr/bin/bash
          - /usr/local/bin/alive.sh
        initialDelaySeconds: 10
        periodSeconds: 60
    - image: docker.io/library/postgres:15-alpine
      name: db
      env:
        - name: POSTGRES_PASSWORD
          value: a
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: cloud-db-pvc
    - image: docker.io/nextcloud/aio-imaginary
      name: imaginary
    - image: docker.io/library/redis:7-alpine
      name: redis
      volumeMounts:
        - mountPath: /data
          name: cloud-redis-pvc
  volumes:
    - name: cloud-pvc
      hostPath:
        path: /mnt/persist/cloud
    - name: cloud-db-pvc
      hostPath:
        path: /mnt/persist/cloud/db
    - name: cloud-preview-pvc
      persistentVolumeClaim:
        claimName: cloud-preview
    - name: cloud-redis-pvc
      persistentVolumeClaim:
        claimName: cloud-redis
