---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate: registry
    io.containers.autoupdate/app: local
  labels:
    app: docs-pod
  name: docs-pod
spec:
  automountServiceAccountToken: false
  containers:
    - name: app
      image: localhost/docs:latest
      ports:
        - containerPort: 8000
          hostPort: 8000
      livenessProbe:
        httpGet:
          port: 8000
        initialDelaySeconds: 60
        periodSeconds: 60
      env:
        - name: PAPERLESS_URL
          value: https://docs.dm-poepperl.de
        - name: PAPERLESS_TIME_ZONE
          value: Europe/Berlin
        - name: PAPERLESS_ADMIN_USER
          value: admin
        - name: PAPERLESS_DBUSER
          value: docs
        - name: PAPERLESS_DBNAME
          value: docs
        - name: PAPERLESS_DBHOST
          value: localhost
        - name: PAPERLESS_OCR_LANGUAGE
          value: deu+eng
        - name: PAPERLESS_OCR_CLEAN
          value: clean-final
        - name: PAPERLESS_OCR_SKIP_ARCHIVE_FILE
          value: with_text
        - name: PAPERLESS_DATA_DIR
          value: /usr/src/paperless/data
        - name: PAPERLESS_MEDIA_ROOT
          value: /usr/src/paperless/data/media
      volumeMounts:
        - mountPath: /usr/src/paperless/consume
          name: docs-scan-pvc
        - mountPath: /usr/src/paperless/data/media/documents/thumbnails
          name: docs-thumbnails-pvc
        - mountPath: /usr/src/paperless/data
          name: docs-pvc
    - name: db
      securityContext:
        runAsGroup: 879
        runAsUser: 879
      env:
        - name: POSTGRES_PASSWORD
          value: a
      image: docker.io/library/postgres:15-alpine
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: docs-db-pvc
    - name: redis
      image: docker.io/library/redis:7-alpine
      volumeMounts:
        - mountPath: /data
          name: docs-redis-pvc
  volumes:
    - name: docs-db-pvc
      hostPath:
        path: /mnt/persist/docs/db
    - name: docs-pvc
      hostPath:
        path: /mnt/persist/docs
    - name: docs-redis-pvc
      persistentVolumeClaim:
        claimName: docs-redis
    - name: docs-thumbnails-pvc
      persistentVolumeClaim:
        claimName: docs-thumbnails
    - name: docs-scan-pvc
      persistentVolumeClaim:
        claimName: docs-scan
