---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate: registry
    io.containers.autoupdate/app: local
  labels:
    app: docs-pod
  name: docs-pod
spec:
  automountServiceAccountToken: false
  containers:
    - name: app
      image: localhost/docs:latest
      ports:
        - containerPort: 8000
      livenessProbe:
        httpGet:
          port: 8000
        periodSeconds: 300
      env:
        - name: PAPERLESS_URL
          value: https://docs.dm-poepperl.de
        - name: PAPERLESS_TIME_ZONE
          value: Europe/Berlin
        - name: PAPERLESS_ADMIN_USER
          value: admin
        - name: PAPERLESS_DBUSER
          value: docs
        - name: PAPERLESS_DBNAME
          value: docs
        - name: PAPERLESS_DBHOST
          value: localhost
        - name: PAPERLESS_DBENGINE
          value: postgresql
        - name: PAPERLESS_OCR_LANGUAGE
          value: deu+eng
        - name: PAPERLESS_OCR_CLEAN
          value: clean-final
        - name: PAPERLESS_OCR_SKIP_ARCHIVE_FILE
          value: with_text
        - name: PAPERLESS_DATA_DIR
          value: /usr/src/paperless/data
        - name: PAPERLESS_MEDIA_ROOT
          value: /usr/src/paperless/data/media
        - name: PAPERLESS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: docs_key
              key: key
      volumeMounts:
        - mountPath: /usr/src/paperless/consume
          name: docs-scan-pvc
        - mountPath: /usr/src/paperless/data/media/documents/thumbnails
          name: docs-thumbnails-pvc
        - mountPath: /usr/src/paperless/data
          name: docs-pvc
        - mountPath: /usr/src/paperless/scripts/passwords.txt
          name: pdf-passwords
          readOnly: true
    - name: db
      securityContext:
        runAsGroup: 879
        runAsUser: 879
      env:
        - name: POSTGRES_PASSWORD
          value: a
      livenessProbe:
        exec:
          command:
            - pg_isready
            - -U
            - postgres
        periodSeconds: 300
      image: docker.io/library/postgres:18-alpine
      volumeMounts:
        - mountPath: /var/lib/postgresql
          name: docs-db-pvc
    - name: redis
      image: docker.io/valkey/valkey:8-alpine
      livenessProbe:
        exec:
          command:
            - redis-cli
            - ping
        periodSeconds: 300
  volumes:
    - name: docs-db-pvc
      hostPath:
        path: /var/mnt/persist/docs/db
    - name: docs-pvc
      hostPath:
        path: /var/mnt/persist/docs
    - name: docs-thumbnails-pvc
      persistentVolumeClaim:
        claimName: docs-thumbnails
    - name: docs-scan-pvc
      persistentVolumeClaim:
        claimName: docs-scan
    - name: pdf-passwords
      hostPath:
        path: /var/mnt/persist/secrets/pdf_passwords.txt
        type: File
