---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate: registry
  labels:
    app: immich-pod
  name: immich-pod
spec:
  containers:
    - name: app
      image: ghcr.io/immich-app/immich-server:release
      volumeMounts:
        - mountPath: /data
          name: immich-pvc
        - mountPath: /mnt/test
          name: test-pvc
        - mountPath: /mnt/cloud
          name: cloud-pvc
      env:
        - name: TZ
          value: Europe/Berlin
        - name: DB_PASSWORD
          value: a
        - name: DB_USERNAME
          value: postgres
        - name: DB_DATABASE_NAME
          value: postgres
        - name: DB_HOSTNAME
          value: localhost
        - name: REDIS_HOSTNAME
          value: localhost
        - name: IMMICH_MACHINE_LEARNING_URL
          value: http://localhost:3003
      ports:
        - name: web
          containerPort: 2283
          hostPort: 8089
    - name: ml
      image: ghcr.io/immich-app/immich-machine-learning:release
      volumes:
        - immich-modelcache-pvc:/cache
    - name: redis
      image: docker.io/valkey/valkey:8-alpine
    - name: db
      image: ghcr.io/immich-app/postgres:17-vectorchord0.4.3
      env:
        - name: POSTGRES_PASSWORD
          value: a
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: immich-db-pvc
  volumes:
    - name: immich-pvc
      hostPath:
        path: /mnt/persist/immich
    - name: test-pvc
      hostPath:
        path: /mnt/persist/test
    - name: immich-db-pvc
      hostPath:
        path: /mnt/persist/immich/db
    - name: cloud-pvc
      hostPath:
        path: /mnt/persist/cloud/data/dmp/files/Bilder
        readOnly: true
    - name: immich-modelcache-pvc
      persistentVolumeClaim:
        claimName: immich-modelcache
