apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate: registry
  labels:
    app: vault-pod
  name: vault-pod
spec:
  automountServiceAccountToken: false
  containers:
    - name: app
      image: ghcr.io/dani-garcia/vaultwarden:alpine
      env:
        - name: TZ
          value: Europe/Berlin
        - name: ICON_CACHE_FOLDER
          value: /var/icons
        - name: ROCKET_PORT
          value: "8087"
        - name: LOG_LEVEL
          value: warn
        - name: DATABASE_URL
          value: postgresql://vault@localhost/vault
        - name: INVITATION_ORG_NAME
          value: Lauras and Dennis' Cloud
        - name: PASSWORD_HINTS_ALLOWED
          value: false
        - name: SIGNUPS_ALLOWED
          value: false
        - name: DOMAIN
          value: https://vault.dm-poepperl.de
        - name: IP_HEADER
          value: X-Forwarded-For
        - name: SMTP_HOST
          value: smtp.strato.de
        - name: SMTP_SECURITY
          value: force_tls
        - name: SMTP_PORT
          value: 465
        - name: SMTP_FROM
          value: cloud@dm-poepperl.de
        - name: SMTP_USERNAME
          value: cloud@dm-poepperl.de
        - name: SMTP_FROM_NAME
          value: L&D Cloud
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloud-smtp
              key: password
        - name: TRASH_AUTO_DELETE_DAYS
          value: 1000
      ports:
        - name: vault
          containerPort: 8087
          hostPort: 8087
      securityContext:
        runAsGroup: 844
        runAsUser: 844
      volumeMounts:
        - mountPath: /data
          name: vault-pvc
    - name: db
      image: docker.io/library/postgres:15-alpine
      env:
        - name: POSTGRES_PASSWORD
          value: a
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: vault-db-pvc
  enableServiceLinks: false
  volumes:
    - name: vault-pvc
      hostPath:
        path: /mnt/persist/vault
    - name: vault-db-pvc
      hostPath:
        path: /mnt/persist/vault/db
